// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxunbjmrixpkwisisajc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dW5iam1yaXhwa3dpc2lzYWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzM3ODQsImV4cCI6MjA2NDcwOTc4NH0.7XHkPwb1ahPgEHvymggXKgRxdjfWzWyyUvBkqftIzUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);